#!/bin/bash

# requres ghostscript
# (e.g. brew install ghostscript)

pdf_compress() {
    # pdf_compress infile outfile
    gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH \
        -sOutputFile="$2" "$1"
}

if [ ! -f "$1" ]; then
    echo "Not exists input file: $1"; exit 1;
fi

if [ -z "$2" ]; then
    # inplace
    infile="$1"
    outfile="$1.tmp"

    pdf_compress "$infile" "$outfile"
    mv $infile $infile.bak
    mv $outfile $infile
else
    # infile -> outfile
    pdf_compress $1 $2
fi
