#!/bin/bash

# requres ghostscript
# (e.g. brew install ghostscript)

usage() {
    echo "Usage: "
    echo "  pdf-compress infile             (inplace convert)"
    echo "  pdf-compress infile outfile     (convert from infile to outfile)"
}

pdf_compress() {
    # pdf_compress infile outfile
    # -dPDFSETTINGS=/screen   -- 72 dpi;
    # -dPDFSETTINGS=/ebook    -- 150 dpi;
    # -dPDFSETTINGS=/printer  -- 300 dpi greyscale;
    # -dPDFSETTINGS=/prepress -- 300 dpi color.
    gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dColorImageResolution=250 -dNOPAUSE -dQUIET -dBATCH \
        -sOutputFile="$2" "$1"
}

if [[ -z "$1" || "$1" == "--help" ]]; then
    usage; exit
fi

if [ ! -f "$1" ]; then
    echo "Input file not exists: $1"; exit 1;
fi

if [ -z "$2" ]; then
    # inplace
    infile="$1"
    outfile="$1.tmp"

    pdf_compress "$infile" "$outfile"
    mv "$infile" "$infile.bak"
    mv "$outfile" "$infile"
else
    # infile -> outfile
    pdf_compress "$1" "$2"
fi
